export const ListOfFilms = [
  {
    id: 1,
      title: "Cat Run 2",
      year: "2014",
      img: "./assests/images/img1.jpg",
      director: "John Stockwell",
      writers: "Andrew MansonMatt Manson",
      nation: "USA",
      content:
        "Cuộc sống của hai sát thủ, một võ sĩ quyền anh, một tay xã hội đen cùng vợ anh ta, và một cặp cướp quán ăn đan xen vào nhau trong bốn câu chuyện về bạo lực và cứu chuộc.",
      isNewUpdate: true,
      embeddedURL: "i83IThQ9ZwA",
      imgVd: "./assests/imageVideo/catrun2.jpg",
    },
  {
    id: 2,
    title: "Sát thủ John Wick: Phần 4",
    year: "2023",
    director: "Chad Stahelski",
    writers: "Shay HattenMichael FinchDerek Kolstad",
    img: "./assests/images/img2.jpg",
    imgBanner: "./assests/imageSlider/john-wick-banner.jpg",
    content:
      "John Wick khám phá ra cách hạ bệ The High Table, nhưng hành trình tìm đến tự do của anh còn lâu mới kết thúc. Anh ta phải đối đầu với một kẻ thù đáng gờm với các mối quan hệ toàn cầu và khả năng biến đồng minh thành kẻ thù...",
    nation: "USA",
    isHot: true,
    isSlider: true,
    embeddedURL: "qEVUtrk8_B4",
    imgVd: "./assests/imageVideo/John Wick 4.jpg",
  },

  {
    id: 3,
    title: "Game of Thrones",
    year: "2011–2019",
    img: "./assests/images/img3.jpg",
    nation: "JPG",
    director: "D.B. Weiss",
    writers: "David BenioffD.B. Weiss",
    content:
      "Trong vùng đất hoang hậu khải huyền, một người phụ nữ nổi dậy chống lại một kẻ thống trị độc tài để tìm kiếm quê hương của mình với sự trợ giúp của một nhóm nữ tù nhân, một người sùng bái tâm thần và một người bị trôi dạt tên là Max.",
    isNewUpdate: true,
    embeddedURL: "KPLWWIOCOOQ",
    imgVd: "./assests/imageVideo/game-of-thrones.jpg",
  },

  {
    id: 4,
    title: "Mad Max: Fury Road",
    year: "2015",
    img: "./assests/images/img4.jpg",
    nation: "USA",
    director: "George Miller",
    writers: "George Miller Brendan McCarthyNick Lathouris",
    content:
      "Trong vùng đất hoang hậu khải huyền, một người phụ nữ nổi dậy chống lại một kẻ thống trị độc tài để tìm kiếm quê hương của mình với sự trợ giúp của một nhóm nữ tù nhân, một người sùng bái tâm thần và một người bị trôi dạt tên là Max.",
    isNewUpdate: true,
    embeddedURL: "hEJnMQG9ev8",
    imgVd: "./assests/imageVideo/maxresdefault.jpg",
  },

  {
    id: 5,
    title: "The Shawshank Redemption",
    year: "1994",
    img: "./assests/images/img55.jpg",
    content:
      "Hai người đàn ông bị giam cầm gắn bó trong nhiều năm, tìm kiếm niềm an ủi và cuối cùng là sự cứu chuộc thông qua những hành vi lịch sự thông thường.",
    nation: "USA",
    director: "Frank Darabont",
    writers: "Stephen KingFrank Darabont",
    isNewUpdate: true,
    embeddedURL: "NmzuHjWmXOc",
    imgVd: "./assests/imageVideo/the_shawshank_redemption.jpg",
  },

  {
    id: 6,
    title: "Avengers: Endgame",
    year: "2019",
    content:
      "Sau những sự kiện tàn khốc của Avengers: Infinity War (2018), vũ trụ đang dần tàn lụi. Với sự giúp đỡ của các đồng minh còn lại, các Avengers tập hợp một lần nữa để đảo ngược hành động của Thanos và khôi phục lại sự cân bằng cho vũ trụ.",
    img: "./assests/images/img5.jpg",
    nation: "USA",
    director: "Stephen KingFrank Darabont",
    writers: "Christopher MarkusStephen McFeelyStan Lee",
    isHot: true,
    isNewUpdate: true,
    embeddedURL: "rrGMENN1iaY",
    imgVd: "./assests/imageVideo/avengers.jpg",
  },

  {
    id: 7,
    title: "The Meg",
    year: "2018",
    content:
      'Taylor là kẻ hèn nhát và bị tâm thần. Năm năm sau, tỷ phú Jack Morris gặp Tiến sĩ Zhang Minway tại một trạm nghiên cứu dưới nước trị giá 1,3 tỷ USD mang tên Mana One mà Morris đã đầu tư. Zhang và con gái ông, Suyin, một nhà hải dương học, giám sát một nhiệm vụ khám phá phần sâu hơn của Rãnh Mariana, bị che giấu bởi một dòng hydro sulfua. Một chiếc tàu lặn được cử xuống đáy biển, nó được điều khiển bởi Lori - vợ cũ của Taylor, cùng với các nhà khoa học DJ, Toshi và "The Wall". Suy luận của họ đã đúng khi họ khám phá ra vô số loài động thực vật chưa từng phát hiện bên dưới lớp thermocline. Một sinh vật khổng lồ va chạm với chiếc tàu lặn khiến nó mất liên lạc với trạm Mana One.',
    img: "./assests/images/img6.jpg",
    nation: "USA",
    director: "Jon Turteltaub",
    writers: "Dean GeorgarisJon HoeberErich Hoeber",
    isNewUpdate: true,
    embeddedURL: "udm5jUA-2bs",
    imgVd: "./assests/imageVideo/themeg.jpg",
  },

  {
    id: 8,
    title: "Se7en",
    year: "1995",
    img: "./assests/images/img7.jpg",
    nation: "USA",
    director: "David Fincher",
    writers: "Andrew Kevin Walker",
    content:
      "Hai thám tử săn lùng một kẻ giết người hàng loạt, kẻ sử dụng bảy tội lỗi chết người làm động cơ của hắn",
    isNewUpdate: true,
    embeddedURL: "znmZoVkCjpI",
    imgVd: "./assests/imageVideo/se7en-facts.jpg",
  },

  {
    id: 9,
    title: "Interstellar",
    year: "2014",
    img: "./assests/images/img8.jpg",
    content:
      "Một nhóm các nhà thám hiểm du hành xuyên qua một lỗ sâu trong không gian với nỗ lực đảm bảo sự sống còn của nhân loại.",
    nation: "USA",
    director: "Christopher Nolan",
    writers: "Christopher Nolan Jonathan Nolan",
    isNewUpdate: true,
    embeddedURL: "QqSp_dwslro",
    imgVd: "./assests/imageVideo/interstellar.jpg",
  },
  {
    id: 10,
    title: "Pirates of the Caribbean: On Stranger Tides",
    year: "2011",
    img: "./assests/images/img9.jpg",
    content:
      "Jack Sparrow và Barbossa bắt tay vào cuộc tìm kiếm suối nguồn tuổi trẻ khó nắm bắt, chỉ để phát hiện ra rằng Râu Đen và con gái của ông ta cũng đang theo đuổi nó.",
    nation: "USA",
    director: "Gore Verbinski",
    writers: "Ted ElliottTerry RossioStuart Beattie",
    isNewUpdate: true,
    embeddedURL: "0BXCVe8Yww4",
    imgVd: "./assests/imageVideo/scale.jpg",
  },
  {
    id: 11,
    title: "Pulp Fiction",
    year: "1994",
    img: "./assests/images/img11.jpg",
    nation: "USA",
    director: "Quentin Tarantino",
    writers: "Quentin Tarantino Roger Avary",
    content:
      "Cuộc sống của hai sát thủ, một võ sĩ quyền anh, một tay xã hội đen cùng vợ anh ta, và một cặp cướp quán ăn đan xen vào nhau trong bốn câu chuyện về bạo lực và cứu chuộc.",
    isNewUpdate: true,
    embeddedURL: "s7EdQ4FqbhY",
    imgVd: "./assests/imageVideo/pulpfiction.jpg",
  },
  {
    id: 12,
    title: "The Super Mario Bros. Movie",
    year: "2023",
    img: "./assests/images/img12.jpg",
    imgBanner: "./assests/imageSlider/mario-banner.jpg",
    content:
      "Tham gia cuộc phiêu lưu của anh em Super Mario. khi họ bắt tay vào một nhiệm vụ ly kỳ qua Vương quốc Nấm đầy mê hoặc.",
    nation: "USA",
    director: "Aaron Horvath",
    writers: " Michael Jelenic, Pierre Leduc",
    isHot: true,
    isSlider: true,
    embeddedURL: "TnGl01FkMMo",
    imgVd: "./assests/imageVideo/mario.jpg",
  },
  {
    id: 13,
    title: "Simulant",
    year: "2023",
    img: "./assests/images/img13.jpg",
    content:
      "Ở một thế giới trong tương lai gần, một người máy tìm kiếm sự giúp đỡ của một hacker toàn cầu nổi tiếng để thoát khỏi mọi giới hạn về suy nghĩ và khả năng của mình. Điều này dẫn đến một cuộc nổi dậy bất ngờ của trí tuệ nhân tạo và đặt ra một cuộc săn lùng của chính phủ để tiêu diệt ý thức ngày càng tăng của máy móc.",
    nation: "USA",
    director: "April Mullen",
    writers: "Ryan Christopher Churchill",
    isHot: true,
    embeddedURL: "YNPf1aMpPbs",
    imgVd: "./assests/imageVideo/simulant.jpg",
  },
  {
    id: 14,
    title: "The Covenant",
    year: "2023",
    content:
      "Giữa cuộc chiến Afghanistan, một phiên dịch viên địa phương dũng cảm, bị ràng buộc bởi một hợp đồng, đã mạo hiểm mạng sống của mình để cõng một trung sĩ bị thương qua nhiều dặm địa hình nguy hiểm.",
    img: "./assests/images/img14.jpg",
    imgBanner: "./assests/imageSlider/theconvenent.jpg",
    nation: "USA",
    director: "Guy Ritchie",
    writers: "Guy RitchieIvan, AtkinsonMarn Davies",
    isHot: true,
    isNewUpdate: true,
    isSlider: true,
    embeddedURL: "02PPMPArNEQ",
    imgVd: "./assests/imageVideo/convenant.jpg",
  },
  {
    id: 15,
    title: "The Mother",
    year: "2023",
    img: "./assests/images/img15.jpg",
    imgBanner: "./assests/imageSlider/themother.jpg",
    content:
      "Nina, cựu đặc vụ NATO với quá khứ bí ẩn, buộc phải giải phóng khả năng chết người để giải cứu con trai khỏi những tên xã hội đen tàn nhẫn. Việc tìm kiếm Max mang đến cơ hội gấp đôi cho Nina - một cơ hội để khơi dậy niềm đam mê nguy hiểm của cô và khả năng mang lại cho con trai cô cuộc sống xứng đáng.",
    nation: "USA",
    director: "Niki Caro",
    writers: "Misha Green, Andrea Berloff, Peter Craig",
    isHot: true,
    isNewUpdate: true,
    isSlider: true,
    embeddedURL: "8BFdFeOS3oM",
    imgVd: "./assests/imageVideo/themother.jpg",
  },
  {
    id: 16,
    title: "Theo Đuổi Một Huyền Thoại",
    year: "2023",
    content:
      "Trải nghiệm hành trình của nhân viên bán giày Sonny Vaccaro khi anh đưa Nike thực hiện nhiệm vụ bảo vệ cầu thủ bóng rổ vĩ đại nhất mọi thời đại, Michael Jordan.",
    img: "./assests/images/img16.jpg",
    nation: "USA",
    director: "Ben Affleck",
    writers: "Alex Convery",
    isHot: true,
    embeddedURL: "0h9vZ52Vals",
    imgVd: "./assests/imageVideo/chase.jpg",
  },
  {
    id: 17,
    title: "Hypnotic",
    year: "2023",
    img: "./assests/images/img17.jpg",
    nation: "USA",
    director: "Robert Rodriguez",
    writers: "Robert Rodriguez, Max Borenstein",
    imgBanner: "./assests/imageSlider/hypnotic.jpg",
    content:
      "Trong bộ phim ly kỳ này, một thám tử đi sâu vào bí ẩn khó hiểu đan xen giữa cô con gái mất tích của anh và sáng kiến bí mật của chính phủ.",
    isHot: true,
    isSlider: true,
    embeddedURL: "FEnsn7CIay0",
    imgVd: "./assests/imageVideo/hypnotic-blogroll-1683756903315.jpg",
  },
  {
    id: 18,
    title: "Come Out Fighting",
    year: "2023",
    img: "./assests/images/img18.jpg",
    imgBanner: "./assests/imageSlider/comeout.jpg",
    content:
      "Trong bộ phim đầy hành động lấy bối cảnh Thế chiến 2 này, một đội lính của Quân đội Hoa Kỳ bắt tay vào nhiệm vụ truy tìm sĩ quan chỉ huy mất tích của họ, người đã biến mất sau chiến tuyến của kẻ thù.",
    nation: "USA",
    director: "Steven Luke",
    writers: "Steven Luke",
    isHot: true,
    isSlider: true,
    embeddedURL: "j2J0TOnD_UY",
    imgVd: "./assests/imageVideo/comeout.jpg",
  },
  {
    id: 19,
    title: "Già Gân Báo Thù",
    year: "2023",
    img: "./assests/images/img19.jpg",
    imgBanner: "./assests/imageSlider/giagan.jpg",
    content:
      "Ở trung tâm của Lapland, một cựu quân nhân tìm thấy một kho báu bằng vàng. Khi cố gắng mang số vàng vào thành phố, ông nằm trong tầm ngắm của một nhóm lính Đức Quốc xã, do một sĩ quan SS tàn nhẫn cầm đầu. Một trận chiến muôn thuở xảy ra khi người anh hùng của chúng ta đấu tranh quyết liệt để giữ lấy những gì thuộc về mình. Ông già gân sẽ chiến thắng hay trở thành nạn nhân trước sức mạnh của Đệ tam Quốc xã? Câu trả lời trong bộ phim sử thi về lòng tham, lòng dũng cảm và sự sống còn này.",
    nation: "USA",
    director: "Jalmari Helander",
    writers: "Jalmari Helander",
    isHot: true,
    isSlider: true,
    embeddedURL: "2NnPzpuU5ao",
    imgVd: "./assests/imageVideo/sisu.jpg",
  },
  {
    id: 20,
    title: "Medellin",
    year: "2023",
    img: "./assests/images/img20.jpg",
    content:
      "Reda tập hợp một phi hành đoàn để giải cứu anh trai khỏi nanh vuốt của những tên tội phạm ma túy Medellin khét tiếng. Nhiệm vụ của họ? Để khởi động một cuộc đột kích táo bạo vào thành trì của bọn bắt cóc ở Colombia.",
    nation: "USA",
    director: "Franck Gastambide",
    writers: "Franck Gastambide, Charles Van Tieghem",
    isHot: true,
    embeddedURL: "nb6YQAlh7bU",
    imgVd: "./assests/imageVideo/MEDELLIN.jpg",
  },
  {
    id: 21,
    title: "BlackBerry",
    year: "2023",
    img: "./assests/images/img21.jpg",
    content:
      "Câu chuyện về chiếc điện thoại thông minh Blackberry mang tính cách mạng đã vươn tới tầm vĩ đại, chỉ để rồi sụp đổ tàn khốc.",
    nation: "USA",
    director: "Matt Johnson",
    writers: "Jacquie McNish, Sean Silcoff, Matt Johnson",
    isHot: true,
    embeddedURL: "fOj0lRfKiVE",
    imgVd: "./assests/imageVideo/blackberry.jpg",
  },
  {
    id: 22,
    title: "Black Lotus ",
    year: "2023",
    img: "./assests/images/img22.jpg",
    content:
      "Một chiến binh đơn độc, từng là thành viên lực lượng đặc biệt, dấn thân vào sứ mệnh giải cứu đứa con gái của bạn anh khỏi nanh vuốt của tổ chức tội phạm khét tiếng.",
    nation: "USA",
    director: "Todor Chapkanov",
    writers: "Tad Daggerhart",
    isHot: true,
    embeddedURL: "iNUUqFssqPs",
    imgVd: "./assests/imageVideo/blacklottus.jpg",
  },
  {
    id: 23,
    title: "Mafia Mamma ",
    year: "2023",
    img: "./assests/images/img23.jpg",
    content:
      "Một bà mẹ thừa kế đế chế mafia của ông nội cô ở Ý. Được cố vấn, cô khiến mọi người chấp nhận địa vị mới như một bà trùm mafia trong công ty gia đình.",
    nation: "USA",
    director: "Catherine Hardwicke",
    writers: "Amanda Sthers, J.Michael Feldman, Debbie Jhoon",
    isHot: true,
    embeddedURL: "e2UNT1pLP6g",
    imgVd: "./assests/imageVideo/mafiamama.jpg",
  },
  {
    id: 24,
    title: "Hachiko ",
    year: "2023",
    img: "./assests/images/img24.jpg",
    content:
      "Ba Tong, chú chó trung thành kiên trung hết lòng vì chủ, chờ đợi cả chục năm sau khi chủ qua đời, là một câu chuyện cảm động chắc chắn sẽ khiến khán giả xúc động.",
    nation: "USA",
    director: "Ang Xu",
    writers: "Liangwen Li, Lin LiAng Xu",
    isHot: true,
    embeddedURL: "QrPyiBGD9nc",
    imgVd: "./assests/imageVideo/hachiko.jpg",
  },
];
